"""init

Revision ID: f2a4ce6e3198

Revises:
Create Date: 2026-02-11 18:01:05.510121

"""

import os
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "f2a4ce6e3198"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _get_schema() -> Union[str, None]:
    """Get the schema based on DB_TYPE. PostgreSQL uses sparkdb_manager schema, MySQL uses None."""
    db_type = os.getenv("DB_TYPE", "postgresql").lower()
    if db_type == "postgresql":
        return "sparkdb_manager"
    return None


def upgrade() -> None:
    schema = _get_schema()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "database_meta",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("uid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("space_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("create_at", sa.DateTime(), nullable=False),
        sa.Column("update_at", sa.DateTime(), nullable=False),
        sa.Column("create_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("update_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema=schema,
    )
    op.create_index(
        (
            op.f("ix_database_meta_name")
            if not schema
            else op.f("ix_sparkdb_manager_database_meta_name")
        ),
        "database_meta",
        ["name"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        (
            op.f("ix_database_meta_space_id")
            if not schema
            else op.f("ix_sparkdb_manager_database_meta_space_id")
        ),
        "database_meta",
        ["space_id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        (
            op.f("ix_database_meta_uid")
            if not schema
            else op.f("ix_sparkdb_manager_database_meta_uid")
        ),
        "database_meta",
        ["uid"],
        unique=False,
        schema=schema,
    )
    op.create_table(
        "schema_meta",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("database_id", sa.BigInteger(), nullable=False),
        sa.Column("schema_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("create_at", sa.DateTime(), nullable=False),
        sa.Column("update_at", sa.DateTime(), nullable=False),
        sa.Column("create_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("update_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema=schema,
    )
    op.create_index(
        (
            op.f("ix_schema_meta_schema_name")
            if not schema
            else op.f("ix_sparkdb_manager_schema_meta_schema_name")
        ),
        "schema_meta",
        ["schema_name"],
        unique=False,
        schema=schema,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    schema = _get_schema()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        (
            op.f("ix_database_meta_uid")
            if not schema
            else op.f("ix_sparkdb_manager_database_meta_uid")
        ),
        table_name="database_meta",
        schema=schema,
    )
    op.drop_index(
        (
            op.f("ix_database_meta_space_id")
            if not schema
            else op.f("ix_sparkdb_manager_database_meta_space_id")
        ),
        table_name="database_meta",
        schema=schema,
    )
    op.drop_index(
        (
            op.f("ix_database_meta_name")
            if not schema
            else op.f("ix_sparkdb_manager_database_meta_name")
        ),
        table_name="database_meta",
        schema=schema,
    )
    op.drop_table("database_meta", schema=schema)
    op.drop_index(
        (
            op.f("ix_schema_meta_schema_name")
            if not schema
            else op.f("ix_sparkdb_manager_schema_meta_schema_name")
        ),
        table_name="schema_meta",
        schema=schema,
    )
    op.drop_table("schema_meta", schema=schema)
    # ### end Alembic commands ###
